version: '3'

services:
  dev:
    image: recipes-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - "3333:3333"
    command: yarn dev:server
